language: java
jdk:
- oraclejdk8

branches:
  only:
  - release

cache:
  directories:
  - $HOME/.m2 # speed up maven

addons:
  ssh_known_hosts: prod.cmlteam.com

before_deploy:
- openssl aes-256-cbc -K $encrypted_b1cdd46199e8_key
  -iv $encrypted_b1cdd46199e8_iv
  -in deploy_rsa.enc
  -out /tmp/deploy_rsa -d
- chmod 600 /tmp/deploy_rsa
#- eval "$(ssh-agent -s)" # TODO
#- ssh-add /tmp/deploy_rsa

deploy:
  provider: script
  skip_cleanup: true
  script: ./.travis.deploy.sh
  on:
    branch: release
