### list files

GET localhost:8080/api/file

### list files sorted size

GET localhost:8080/api/file?sort=size

### list files sorted size,desc

GET localhost:8080/api/file?sort=size,desc

### list files (pageSize=1)

GET localhost:8080/api/file?pageSize=1

### list files (pageSize=1&page=1)

GET localhost:8080/api/file?pageSize=1&page=1

### upload file.txt

POST localhost:8080/api/file/upload
Content-Type: application/json

{
  "name": "file.txt",
  "size": 100,
  "tags": ["text", "document"]
}

### upload cat.jpg

POST localhost:8080/api/file/upload
Content-Type: application/json

{
  "name": "cat.jpg",
  "size": 500000,
  "tags": ["image"]
}

### delete file 1

DELETE localhost:8080/api/file/1

### add tags to file 1

POST localhost:8080/api/file/1/tags
Content-Type: application/json

["tag1", "tag2"]

### remove tags from file 1

DELETE localhost:8080/api/file/1/tags
Content-Type: application/json

["tag1"]

### remove non-existing tag from file 1

DELETE localhost:8080/api/file/1/tags
Content-Type: application/json

["tag2", "tag3"]
