server:
  address: 127.0.0.1
  port: 8080

logRestRequestWebInterceptor:
  enabled: true

s3:
  bucket: # EXTERNAL
  accessKey: # EXTERNAL
  secretKey: # EXTERNAL
  region: us-west-1
  endpoint: https://s3.us-west-1.wasabisys.com

elk:
  host: elk.cmlteam.com
  port: 10443
  application: s3mycloud